import { Card, Cards as C } from "../card";
import { finish } from "./index.internal";

type TestCase = {
  name: string;
  hand: Card[];
  pon?: Card[];
  bonus: Card;
  uraBonus?: Card | null;
  ippatsu?: boolean;
  tsumo?: boolean;
  partner: Card;
  expected: { name: string; point: number }[];
};

describe.each<{ name: string; cases: TestCase[] }>([
  {
    name: "単純形",
    cases: [
      {
        name: "オールペア",
        hand: [C.reimu, C.marisa, C.dai, C.cirno, C.hina, C.parsee],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: 大妖精 & チルノ", point: 1 },
          { name: "ペア: 雛 & パルスィ", point: 1 },
        ],
      },
      {
        name: "トリオ: 同ステ同ステ",
        hand: [C.rumia, C.letty, C.nazu, C.marisa, C.lunasa, C.seiga],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "同じステージ", point: 2 },
        ],
      },
      {
        name: "トリオ: 同ステ連ステ",
        hand: [C.rumia, C.letty, C.nazu, C.keine, C.reimu, C.udonge],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "ステージ連番", point: 3 },
        ],
      },
      {
        name: "トリオ: 連ステ3枚役",
        hand: [C.keine, C.reimu, C.udonge, C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "ステージ連番", point: 3 },
          { name: "NO NAME", point: 4 },
        ],
      },
      {
        name: "トリオ: 3枚役3枚役",
        hand: [C.dai, C.koa, C.nanashi, C.sunny, C.luna, C.star],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "三妖精", point: 6 },
          { name: "NO NAME", point: 4 },
          { name: "ペア: 大妖精 & サニー", point: 1 },
        ],
      },
      {
        name: "トリオ: 3枚役ポン",
        hand: [C.rumia, C.letty, C.nazu],
        pon: [C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "鳴き", point: -2 },
        ],
      },
      {
        name: "トリオ: 同ステポン",
        hand: [C.dai, C.koa, C.nanashi],
        pon: [C.rumia, C.letty, C.nazu],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "鳴き", point: -2 },
        ],
      },
      {
        name: "カルテット",
        hand: [C.reimu, C.marisa, C.fran, C.minoriko, C.koisi, C.yorihime],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "妹's", point: 9 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
        ],
      },
      {
        name: "カルテット: ポン",
        hand: [C.reimu, C.marisa],
        pon: [C.fran, C.minoriko, C.koisi, C.yorihime],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "妹's", point: 9 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "鳴き", point: -2 },
        ],
      },
      {
        name: "セクステット: 6枚役",
        hand: [C.dai, C.koa, C.lilyw, C.sizuha, C.momiji, C.kisume],
        bonus: C.reimu,
        partner: C.reimu,
        expected: [
          { name: "中ボス", point: 30 },
          { name: "ペア: 大妖精 & リリーW", point: 1 },
        ],
      },
      {
        name: "セクステット: 一色",
        hand: [C.renko, C.reisen, C.yorihime, C.sunny, C.star, C.korin],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [{ name: "その他シリーズ", point: 5 }],
      },
      {
        name: "セクステット: 3枚ポン",
        hand: [C.koa, C.sakuya, C.fran],
        pon: [C.rumia, C.cirno, C.meirin],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "東方紅魔郷", point: 5 },
          { name: "鳴き", point: -2 },
        ],
      },
      {
        name: "セクステット: 4枚ポン",
        hand: [C.kisume, C.parsee],
        pon: [C.satori, C.orin, C.utuho, C.koisi],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "東方地霊殿", point: 5 },
          { name: "地霊殿＋", point: 5 },
          { name: "地霊殿", point: 4 },
          { name: "ペア: さとり & 燐", point: 1 },
          { name: "ペア: さとり & 空", point: 1 },
          { name: "ペア: さとり & こいし", point: 1 },
          { name: "ペア: 燐 & 空", point: 1 },
          { name: "鳴き", point: -2 },
        ],
      },
    ],
  },
  {
    name: "複合形",
    cases: [
      {
        name: "オールペア形の同ステ同ステ",
        hand: [C.cirno, C.aya, C.marisa, C.pache, C.hina, C.parsee],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "同じステージ", point: 2 },
          { name: "ペア: 魔理沙 & パチュリー", point: 1 },
          { name: "ペア: チルノ & 文", point: 1 },
          { name: "ペア: 雛 & パルスィ", point: 1 },
        ],
      },
      {
        name: "同ステ同ステ形のダマオールペア",
        hand: [C.cirno, C.aya, C.marisa, C.pache, C.hina, C.parsee],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "ペア: 魔理沙 & パチュリー", point: 1 },
          { name: "ペア: チルノ & 文", point: 1 },
          { name: "ペア: 雛 & パルスィ", point: 1 },
        ],
      },
      {
        name: "同ステ同ステ形の3枚役3枚役",
        hand: [C.reimu, C.marisa, C.murasa, C.sakuya, C.komachi, C.futo],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "妖々夢自機", point: 4 },
          { name: "NICE BOAT.", point: 4 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: 小町 & ムラサ", point: 1 },
        ],
      },
      {
        name: "オールペア形のカルテット",
        hand: [C.nitori, C.momiji, C.aya, C.suika, C.reimu, C.marisa],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "妖怪の山", point: 9 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: 霊夢 & 文", point: 1 },
          { name: "ペア: 霊夢 & 萃香", point: 1 },
          { name: "ペア: 魔理沙 & にとり", point: 1 },
          { name: "ペア: にとり & 椛", point: 1 },
          { name: "ペア: にとり & 文", point: 1 },
          { name: "ペア: 椛 & 文", point: 1 },
        ],
      },
      {
        name: "トリオ形のカルテット",
        hand: [C.cirno, C.meirin, C.pache, C.sunny, C.luna, C.star],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "妖精大戦争", point: 5 },
          { name: "三妖精", point: 6 },
          { name: "ペア: 美鈴 & パチュリー", point: 1 },
        ],
      },
      {
        name: "オールペア形の一色",
        hand: [C.toyohime, C.yorihime, C.korin, C.nanashi, C.renko, C.merry],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "その他シリーズ", point: 5 },
          { name: "ペア: 豊姫 & 依姫", point: 1 },
          { name: "ペア: 霖之助 & 本読妖怪", point: 1 },
          { name: "ペア: メリー & 蓮子", point: 1 },
        ],
      },
      {
        name: "トリオ形の一色",
        hand: [C.letty, C.chen, C.alice, C.lunasa, C.youmu, C.yuyuko],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "東方妖々夢", point: 5 },
          { name: "ペア: 橙 & 妖夢", point: 1 },
          { name: "ペア: 妖夢 & 幽々子", point: 1 },
        ],
      },
      {
        name: "カルテット形の一色",
        hand: [C.tewi, C.udonge, C.eirin, C.kaguya, C.reimu, C.marisa],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "東方永夜抄", point: 5 },
          { name: "永遠亭", point: 9 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: てゐ & 鈴仙", point: 1 },
          { name: "ペア: てゐ & 永琳", point: 1 },
          { name: "ペア: 鈴仙 & 永琳", point: 1 },
          { name: "ペア: 鈴仙 & 輝夜", point: 1 },
          { name: "ペア: 永琳 & 輝夜", point: 1 },
        ],
      },
    ],
  },
  {
    name: "ボーナス",
    cases: [
      {
        name: "一発",
        hand: [C.rumia, C.letty, C.nazu, C.marisa, C.lunasa, C.seiga],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        ippatsu: true,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "一発", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "同じステージ", point: 2 },
        ],
      },
      {
        name: "メンゼンツモ",
        hand: [C.rumia, C.letty, C.nazu, C.marisa, C.lunasa, C.seiga],
        bonus: C.sizuha,
        tsumo: true,
        partner: C.sizuha,
        expected: [
          { name: "メンゼンツモ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "同じステージ", point: 2 },
        ],
      },
      {
        name: "ボーナスカード",
        hand: [C.rumia, C.letty, C.nazu, C.dai, C.koa, C.nanashi],
        bonus: C.rumia,
        partner: C.sizuha,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "ボーナスカード", point: 1 },
        ],
      },
      {
        name: "裏ボーナスカード",
        hand: [C.rumia, C.letty, C.nazu, C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        uraBonus: C.rumia,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "裏ボーナスカード", point: 1 },
        ],
      },
      {
        name: "パートナーボーナス",
        hand: [C.rumia, C.letty, C.nazu, C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        partner: C.rumia,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "パートナーボーナス", point: 1 },
        ],
      },
      {
        name: "パートナーボーナス+",
        hand: [C.rumia, C.letty, C.nazu, C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        partner: C.koa,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "パートナーボーナス+", point: 2 },
        ],
      },
      {
        name: "パートナーフィニッシュ",
        hand: [C.rumia, C.letty, C.nazu, C.dai, C.koa, C.nanashi],
        bonus: C.sizuha,
        partner: C.nanashi,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "NO NAME", point: 4 },
          { name: "パートナーボーナス+", point: 2 },
          { name: "パートナーフィニッシュ", point: 1 },
        ],
      },
    ],
  },
  {
    name: "役含み",
    cases: [
      {
        name: "3枚役含みオールペア",
        hand: [C.dai, C.cirno, C.koa, C.pache, C.korin, C.nanashi],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "NO NAME", point: 4 },
          { name: "ペア: 大妖精 & チルノ", point: 1 },
          { name: "ペア: 小悪魔 & パチュリー", point: 1 },
          { name: "ペア: 霖之助 & 本読妖怪", point: 1 },
        ],
      },
      {
        name: "4枚役含みオールペア",
        hand: [C.mystia, C.aya, C.orin, C.utuho, C.hatate, C.kyoko],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "鳥4", point: 5 },
          { name: "カラス", point: 4 },
          { name: "ペア: ミスティア & 響子", point: 1 },
          { name: "ペア: 文 & はたて", point: 1 },
          { name: "ペア: 燐 & 空", point: 1 },
        ],
      },
      {
        name: "ステージ◯◯ボスとオールペアは複合しない",
        hand: [C.eirin, C.kaguya, C.suika, C.tenshi, C.kanako, C.utuho],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "ペア: 永琳 & 輝夜", point: 1 },
          { name: "ペア: 神奈子 & 空", point: 1 },
          { name: "ペア: 萃香 & 天子", point: 1 },
        ],
      },
      {
        name: "4枚役含みトリオ",
        hand: [C.reimu, C.lunasa, C.satori, C.orin, C.utuho, C.koisi],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "ステージ連番", point: 3 },
          { name: "地霊殿＋", point: 5 },
          { name: "地霊殿", point: 4 },
          { name: "ペア: さとり & 燐", point: 1 },
          { name: "ペア: さとり & 空", point: 1 },
          { name: "ペア: さとり & こいし", point: 1 },
          { name: "ペア: 燐 & 空", point: 1 },
        ],
      },
      {
        name: "カルテット形のポン固定トリオ",
        hand: [C.cirno, C.meirin, C.pache],
        pon: [C.sunny, C.luna, C.star],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "ステージ連番", point: 3 },
          { name: "妖精大戦争", point: 5 },
          { name: "三妖精", point: 6 },
          { name: "ペア: 美鈴 & パチュリー", point: 1 },
          { name: "鳴き", point: -2 },
        ],
      },
      {
        name: "ステージ◯◯ボス",
        hand: [C.marisa, C.lunasa, C.merlin, C.lyrica, C.satori, C.seiga],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "同じステージ", point: 2 },
          { name: "ステージ4ボス", point: 5 },
          { name: "プリズムリバーライブ", point: 6 },
        ],
      },
      {
        name: "3枚役含みカルテット",
        hand: [C.fran, C.yukari, C.mokou, C.suika, C.eirin, C.kaguya],
        bonus: C.sizuha,
        uraBonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "文花帖-LEVEL EX", point: 9 },
          { name: "蓬莱人", point: 4 },
          { name: "ペア: 紫 & 萃香", point: 1 },
          { name: "ペア: 永琳 & 輝夜", point: 1 },
          { name: "ペア: 輝夜 & 妹紅", point: 1 },
        ],
      },
      {
        name: "3枚役含み一色",
        hand: [C.toyohime, C.yorihime, C.reisen, C.korin, C.renko, C.kasen],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "その他シリーズ", point: 5 },
          { name: "儚月抄", point: 4 },
          { name: "ペア: 豊姫 & 依姫", point: 1 },
        ],
      },
      {
        name: "4枚役含み一色",
        hand: [C.tewi, C.udonge, C.eirin, C.kaguya, C.wriggle, C.mystia],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "東方永夜抄", point: 5 },
          { name: "永遠亭", point: 9 },
          { name: "ペア: てゐ & 鈴仙", point: 1 },
          { name: "ペア: てゐ & 永琳", point: 1 },
          { name: "ペア: 鈴仙 & 永琳", point: 1 },
          { name: "ペア: 鈴仙 & 輝夜", point: 1 },
          { name: "ペア: 永琳 & 輝夜", point: 1 },
        ],
      },
      {
        name: "命蓮寺",
        hand: [C.nazu, C.ichirin, C.unzan, C.murasa, C.syou, C.byakuren],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "命蓮寺", point: 30 },
          { name: "東方星蓮船", point: 5 },
          { name: "DS-LEVEL5", point: 4 },
          { name: "ペア: ナズーリン & 星", point: 1 },
          { name: "ペア: 一輪 & 雲山", point: 1 },
          { name: "ペア: 一輪 & ムラサ", point: 1 },
          { name: "ペア: 一輪 & 白蓮", point: 1 },
          { name: "ペア: ムラサ & 白蓮", point: 1 },
          { name: "ペア: 星 & 白蓮", point: 1 },
        ],
      },
      {
        name: "ポン",
        hand: [C.sanae, C.suwako],
        pon: [C.ran, C.yukari, C.eirin, C.kanako],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "エイトフォー", point: 9 },
          { name: "守矢神社", point: 4 },
          { name: "ペア: 藍 & 紫", point: 1 },
          { name: "ペア: 早苗 & 神奈子", point: 1 },
          { name: "ペア: 早苗 & 諏訪子", point: 1 },
          { name: "ペア: 神奈子 & 諏訪子", point: 1 },
          { name: "鳴き", point: -2 },
        ],
      },
    ],
  },
  {
    name: "特定ケース",
    cases: [
      {
        name: "理論値",
        hand: [C.nazu, C.ichirin, C.unzan, C.murasa, C.syou, C.byakuren],
        bonus: C.nazu,
        uraBonus: C.ichirin,
        ippatsu: true,
        tsumo: true,
        partner: C.byakuren,
        expected: [
          { name: "リーチ", point: 1 },
          { name: "一発", point: 1 },
          { name: "メンゼンツモ", point: 1 },
          { name: "命蓮寺", point: 30 },
          { name: "東方星蓮船", point: 5 },
          { name: "DS-LEVEL5", point: 4 },
          { name: "ペア: ナズーリン & 星", point: 1 },
          { name: "ペア: 一輪 & 雲山", point: 1 },
          { name: "ペア: 一輪 & ムラサ", point: 1 },
          { name: "ペア: 一輪 & 白蓮", point: 1 },
          { name: "ペア: ムラサ & 白蓮", point: 1 },
          { name: "ペア: 星 & 白蓮", point: 1 },
          { name: "ボーナスカード", point: 1 },
          { name: "裏ボーナスカード", point: 1 },
          { name: "パートナーボーナス", point: 1 },
          { name: "パートナーフィニッシュ", point: 1 },
        ],
      },
      {
        name: "多役",
        hand: [C.reimu, C.marisa, C.alice, C.sakuya, C.youmu, C.sanae],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "同じステージ", point: 2 },
          { name: "神霊廟自機", point: 5 },
          { name: "永夜抄人間", point: 5 },
          { name: "旧作-怪綺談", point: 4 },
          { name: "妖々夢自機", point: 4 },
          { name: "星蓮船自機", point: 4 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: 霊夢 & アリス", point: 1 },
          { name: "ペア: 霊夢 & 早苗", point: 1 },
          { name: "ペア: 魔理沙 & アリス", point: 1 },
        ],
      },
      {
        name: "多ペア",
        hand: [C.reimu, C.marisa, C.korin, C.nitori, C.momiji, C.aya],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [
          { name: "オールペア", point: 4 },
          { name: "ペア: 霊夢 & 魔理沙", point: 1 },
          { name: "ペア: 霊夢 & 文", point: 1 },
          { name: "ペア: 霊夢 & 霖之助", point: 1 },
          { name: "ペア: 魔理沙 & にとり", point: 1 },
          { name: "ペア: 魔理沙 & 霖之助", point: 1 },
          { name: "ペア: にとり & 椛", point: 1 },
          { name: "ペア: にとり & 文", point: 1 },
          { name: "ペア: 椛 & 文", point: 1 },
        ],
      },
    ],
  },
  {
    name: "未アガリ",
    cases: [
      {
        name: "3ペアに分けられないオールペア",
        hand: [C.reimu, C.marisa, C.remi, C.alice, C.yukari, C.sanae],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [],
      },
      {
        name: "リーチなしステ連同ステロン",
        hand: [C.rumia, C.cirno, C.meirin, C.sakuya, C.youmu, C.reisen],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [],
      },
      {
        name: "3枚役+ステに分けられないトリオ",
        hand: [C.rumia, C.cirno, C.meirin, C.sanae, C.youmu, C.reisen],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [],
      },
      {
        name: "4枚役+ペアに分けられないカルテット",
        hand: [C.reimu, C.marisa, C.youmu, C.sanae, C.yuyuko, C.remi],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [],
      },
      {
        name: "ポンを跨ぐカルテット",
        hand: [C.suika, C.eirin, C.kaguya],
        pon: [C.fran, C.yukari, C.mokou],
        bonus: C.sizuha,
        partner: C.sizuha,
        expected: [],
      },
    ],
  },
])("$name", ({ cases }: { cases: TestCase[] }) => {
  it.each(cases)(
    "$name",
    ({
      hand,
      pon = [],
      bonus,
      uraBonus = null,
      ippatsu = false,
      tsumo = false,
      partner,
      expected,
    }) => {
      const actual = finish(
        hand,
        pon,
        bonus,
        uraBonus,
        ippatsu,
        tsumo,
        partner
      );
      expect(actual).toEqual(expected);
    }
  );
});
